### ISSUE TITLE
Use FASTQ input

### ISSUE THREAD

**Issue by mgalardini** [bede/tictax#1]
Hi,

thanks for the awesome software; an obvious improvements for it would be reading FASTQ files (better if it could handle gzipped ones as well).
Right now to do that you first have to convert them to FASTA:

    zcat READS.fq.gz | python -c "import sys;from Bio import SeqIO;_ = [SeqIO.write(s, sys.stdout, 'fasta') for s in SeqIO.parse(sys.stdin, 'fastq')]" > READS.fasta

Thank you very much,
Marco

**Comment by bede** [comment]
Hi Marco,
Good suggestion! I'll look into it.

Bede

**Comment by bede** [comment]
Added fastq and gzip support in 67fca75a4a6c85869ab221c3bbdaed03523444ea

Changes not yet pushed to PyPI. Thanks for the feedback : )

**Comment by mgalardini** [comment]
Hi,

thanks for the proposed fix! Unfortunately it is not working well for my gzipped fastq files, but I wouldn't know why? How can I help you debug the problem?

Marco

**Comment by bede** [comment]
I should probably do some more testing. What's the command you used including file
extension? and the error? If you can email me the fastq too that'd help, but I understand
if not.

**Comment by mgalardini** [comment]
Hi,

here's the two commands used; the sequences are the same, one plain text fastq and one gzipped

```
tictax kmer-lca test.fq
Classifying sequences…
>NB501598:229:HKJM5AFXX:1:11101:14351:1419 one_codex_rt|543|Enterobacteriaceae|family|Bacteria;Proteobacteria;Gammaproteobacteria;Enterobacterales
TGAATTTACCAGCGTACCATTATTTAAAGATGAAATGGTGCTGGTAGCCAGCAAAAATCA
TCCAACAATTAAGGGCCCGTTACTGAAACATGATGTTTATAACGAACAACATGCGGCGGT
TTCGCTCGATCGTTTCGCGTCATTTAGTCA
[...]
```

```
tictax kmer-lca test.gz
Classifying sequences…
✓📌 ✓📌 ✓📌 ✓📌 ✓📌 ✓📌 ✓📌 ✓📌 ✓📌 ✓📌
```

Will send you a small sample via email, thanks a lot for the help and support.
Marco

**Comment by bede** [comment]
Ok, FASTQ autodetection only works for the extensions 'fastq', 'fq', 'fastq.gz' and 'fq.gz'
…Without which tictax assumes fasta input.

I've added a `--fastq` flag to override the autodetection in 8663434792a35182d138aee07bde1cbf88e190fd

The test file you sent me is classified in ~8s

**Comment by mgalardini** [comment]
Hi,

thanks for the fix: it works like a charm on the test file, but I get the following error when using the whole file (150MB):

```
tictax kmer-lca --progress -f input.gz > /dev/null                                                                    
Classifying sequences…
  0%|                                                                                                                                                                             | 0/1594659 [00:00<?, ?it/s]

Traceback (most recent call last):
  File "[...]/lib/python3.5/site-packages/tictax/tictax.py", line 67, in oc_classify_single
    async with session.post(url, data=payload, timeout=600) as response:
  File "[...]/lib/python3.5/site-packages/aiohttp/client.py", line 626, in __aenter__
    self._resp = yield from self._coro
  File "[...]/lib/python3.5/site-packages/aiohttp/client.py", line 295, in _request
    break
  File "[...]/lib/python3.5/site-packages/aiohttp/helpers.py", line 695, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/bin/tictax", line 9, in <module>
    load_entry_point('tictax==0.1.2', 'console_scripts', 'tictax')()
  File "[...]/lib/python3.5/site-packages/tictax/cli.py", line 31, in main
    parser.dispatch()
  File "[...]/lib/python3.5/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "[...]/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "[...]/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "[...]/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "[...]/lib/python3.5/site-packages/tictax/cli.py", line 24, in kmer_lca
    True))
  File "[...]/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "[...]/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "[...]/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "[...]/lib/python3.5/site-packages/tictax/tictax.py", line 116, in oc_classify
    response = await f
  File "[...]/lib/python3.5/asyncio/tasks.py", line 500, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "[...]/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "[...]/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "[...]/lib/python3.5/site-packages/tictax/tictax.py", line 98, in classify_taxify
    classification = await oc_classify_single(oc_session, sequence_id, sequence)
  File "[...]/lib/python3.5/site-packages/tictax/tictax.py", line 69, in oc_classify_single
    except (asyncio.TimeoutError, aiohttp.errors.ClientOSError, json.decoder.JSONDecodeError):
AttributeError: module 'aiohttp' has no attribute 'errors'
```

Maybe the sequences are too many?

Best,
Marco

p.s. I've redacted the paths in the stacktrace

**Comment by bede** [comment]
Thanks for your persistence Marco! I haven't tested this tool with more than a few thousand seqs at a time so I'm not especially suprised that you've found an issue. Give me a few days to try and reproduce and fix.

Best,
Bede

**Comment by bede** [comment]
Closing this and opening https://github.com/bede/tictax/issues/2
